### PR TITLE
feat: adding vision_annotation workflows for images

### PR DESCRIPTION
**Pull request by vaibhav-malpani**
With the below changes, it will add the ability to make image annotations from workflows.

sample request:
`{ "requests": [ { "image": { "source": { "gcsImageUri": "gs://bucket-name/image.jpg" } }, "features": [ { "type": "LABEL_DETECTION", "maxResults": 1 } ] } ] }`

### CODE REVIEW

**Comment by averikitsch** [comment]
Please fix the lint error: https://github.com/GoogleCloudPlatform/workflows-samples/actions/runs/4635146100

**Comment by vaibhav-malpani** [comment]
> Please fix the lint error: https://github.com/GoogleCloudPlatform/workflows-samples/actions/runs/4635146100

Hi @averikitsch , Can you please help me with this?? No matter how much i try i get the same issue while trying to run yamllint on my local machine.

**Comment by averikitsch** [comment]
In my IDE I had to change the end of line sequence from CRLF to LF: https://medium.com/bootdotdev/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf-e1583bf0f0b6. I tried to see if the github editor would fix it, but the last commit didn't.

**Comment by vaibhav-malpani** [comment]
> In my IDE I had to change the end of line sequence from CRLF to LF: https://medium.com/bootdotdev/how-to-get-consistent-line-breaks-in-vs-code-lf-vs-crlf-e1583bf0f0b6. I tried to see if the github editor would fix it, but the last commit didn't.

Same happened with my IDE. I also tried it on sublime and event on github.dev 

Is there any way to skip this check?

**Comment by vaibhav-malpani** [comment]
Got it! Made the changes in latest commit.

**Review by averikitsch — APPROVED** [review]

**Comment by averikitsch** [comment]
Perfect. Thank you for your contribution!

**Pull request merged**
