### PR TITLE
docs: Write error map elements to log for custom predicate

### PR DESCRIPTION
**Pull request by camiekim**
Per b/313661644

### CODE REVIEW

**Comment by camiekim** [comment]
Hi @grayside, @averikitsch, could one of you pls review this PR soon? thanks!

**Review by iennae — APPROVED** [review]
LGTM

In the future, it'd be helpful to have the text that will be used to describe this in updated pages to provide context for reviews. I get why using the error logs as the example to do this step, but effectively this is logging errors as INFO (so it'd be helpful to know how this would be described) as I wouldn't recommend crossing the streams of severity INFO and errors (could use the name log_response_code instead of log_error_code and that would fix this nit).   

For future reviewers, I did deploy this to Cloud Workflows and it works as expected. 

Outside of this PR, I didn't see a place that described response codes in numeric form .. I did find https://cloud.google.com/workflows/docs/reference/syntax/error-types where everything is text. Do we have a place where we document numeric error codes expected?

**Comment by iennae** [comment]
@camiekim do you need me to merge as well or did you want to?

**Comment by camiekim** [comment]
Thanks, @iennae. In the future, I'll make sure to include more context instead of just pointing to the bug and CL.

**Pull request merged**
